### ISSUE TITLE
Confusing Contributor Checklist in the issue template

### ISSUE THREAD

**Issue by whot** [input-leap/input-leap#1709]
### What happened?

Every time I read the template I get confused on whether I need to tick this or not:

```
* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory) 
```

It's clear enough for user-visible changes but for general cleanups? Feels like I *should* tick it but that's not right either :)

How about a two-checkbox either/or like this:

```
* [ ] This is a user-visible change and I have created a file...
* [ ] This is not a user-visible change
```
